package br.com.escola.peopleservice.application.service;

import java.util.List;

import org.springframework.stereotype.Service;

import br.com.escola.peopleservice.application.dto.PeopleTransactionalReadModelExpansionPlan;
import br.com.escola.peopleservice.application.dto.PeopleTransactionalReadModelExpansionPlan.TableExpansionDecision;

@Service
public class PeopleTransactionalReadModelExpansionPlanner {

    public PeopleTransactionalReadModelExpansionPlan planejarProximaFatiaTransacional() {
        return new PeopleTransactionalReadModelExpansionPlan(
                "student_responsible_backfill_reconciliation_prepared_without_cutover",
                "close_phase_65_and_plan_next_people_service_scope",
                "pessoa_student_responsible_read_model",
                true,
                true,
                false,
                List.of(
                        new TableExpansionDecision(
                                "pessoa",
                                "id_pessoa",
                                List.of(
                                        "id_pessoa",
                                        "id_escola",
                                        "escola_nome",
                                        "nome_completo",
                                        "cpf",
                                        "rg",
                                        "orgao_emissor_rg",
                                        "uf_rg",
                                        "email",
                                        "telefone",
                                        "data_nascimento",
                                        "sexo",
                                        "nome_social",
                                        "nacionalidade",
                                        "naturalidade",
                                        "ativo",
                                        "created_at",
                                        "updated_at"),
                                List.of("catalogo_local_tipo_pessoa_reconciliado"),
                                List.of("buscarPorId"),
                                false,
                                true,
                                true,
                                true,
                                "identity_local_read_already_prepared_with_mandatory_fallback"),
                        new TableExpansionDecision(
                                "pessoa_tipo_pessoa",
                                "id_pessoa_tipo_pessoa",
                                List.of("id_pessoa_tipo_pessoa", "id_pessoa", "id_tipo_pessoa", "created_at"),
                                List.of("pessoa", "tipo_pessoa"),
                                List.of("buscarPorId"),
                                false,
                                true,
                                true,
                                true,
                                "identity_local_read_dependency_already_prepared"),
                        new TableExpansionDecision(
                                "aluno",
                                "id_aluno",
                                List.of(
                                        "id_aluno",
                                        "nome_completo",
                                        "cpf",
                                        "email",
                                        "telefone",
                                        "data_nascimento",
                                        "created_at",
                                        "id_pessoa"),
                                List.of("pessoa"),
                                List.of("consultarCadastro"),
                                true,
                                true,
                                true,
                                false,
                                "student_responsible_backfill_reconciliation_prepared_for_current_consultarCadastro_contract"),
                        new TableExpansionDecision(
                                "responsavel",
                                "id_responsavel",
                                List.of(
                                        "id_responsavel",
                                        "nome_completo",
                                        "cpf",
                                        "email",
                                        "telefone",
                                        "created_at",
                                        "id_pessoa"),
                                List.of("pessoa"),
                                List.of("consultarCadastro"),
                                true,
                                true,
                                true,
                                false,
                                "student_responsible_backfill_reconciliation_prepared_for_current_consultarCadastro_contract"),
                        new TableExpansionDecision(
                                "aluno_responsavel",
                                "id_aluno_responsavel",
                                List.of(
                                        "id_aluno_responsavel",
                                        "id_aluno",
                                        "id_responsavel",
                                        "created_at"),
                                List.of("aluno", "responsavel"),
                                List.of("consultarCadastro"),
                                true,
                                true,
                                true,
                                false,
                                "student_responsible_backfill_reconciliation_prepared_for_current_consultarCadastro_contract"),
                        new TableExpansionDecision(
                                "endereco",
                                "id_endereco",
                                List.of(
                                        "id_endereco",
                                        "cep",
                                        "logradouro",
                                        "numero",
                                        "complemento",
                                        "bairro",
                                        "cidade",
                                        "uf",
                                        "created_at",
                                        "updated_at"),
                                List.of("pessoa_endereco", "tipo_endereco"),
                                List.of(),
                                false,
                                false,
                                false,
                                false,
                                "not_exposed_by_current_consultarCadastro_contract"),
                        new TableExpansionDecision(
                                "pessoa_endereco",
                                "id_pessoa_endereco",
                                List.of(
                                        "id_pessoa_endereco",
                                        "id_pessoa",
                                        "id_endereco",
                                        "id_tipo_endereco",
                                        "principal",
                                        "created_at"),
                                List.of("pessoa", "endereco", "tipo_endereco"),
                                List.of(),
                                false,
                                false,
                                false,
                                false,
                                "not_exposed_by_current_consultarCadastro_contract")),
                List.of(
                        "keep-current-identity-local-read-behind-green-reconciliation",
                        "keep-consultarCadastro-on-monolith-until-student-responsible-backfill-is-green",
                        "do-not-add-address-schema-for-current-consultarCadastro-contract",
                        "define-student-responsible-read-model-without-owning-writes",
                        "run-student-responsible-schema-migration-only-with-explicit-opt-in",
                        "run-student-responsible-backfill-and-reconciliation-only-with-explicit-opt-in",
                        "keep-pii-read-model-without-public-exposure",
                        "keep-school-scope-as-copied-identifier-without-people-service-owning-tenant",
                        "define-reconciliation-by-student-responsible-link",
                        "keep-monolith-as-authority-for-all-writes"),
                List.of(
                        "funcionario",
                        "professor",
                        "endereco",
                        "pessoa_endereco",
                        "pessoa_documento"),
                List.of(
                        "disable-people.shadow.local-persistence.migration-enabled",
                        "keep-pessoa-identity-local-read-on-monolith-fallback",
                        "keep-read-model-cutover-disabled-for-transactional-routes",
                        "disable-people.shadow.local-persistence.read-model-cutover-enabled",
                        "keep-consultarCadastro-on-monolith-proxy",
                        "disable-people.shadow.local-persistence.enabled-if-operational-risk-appears"));
    }
}
