package br.com.escola.peopleservice.application.service;

import java.util.List;

import org.springframework.stereotype.Service;

import br.com.escola.peopleservice.application.dto.PeopleTransactionalReadModelExpansionPlan;
import br.com.escola.peopleservice.application.dto.PeopleTransactionalReadModelExpansionPlan.TableExpansionDecision;

@Service
public class PeopleTransactionalReadModelExpansionPlanner {

    public PeopleTransactionalReadModelExpansionPlan planejarProximaFatiaTransacional() {
        return new PeopleTransactionalReadModelExpansionPlan(
                "address_local_read_port_contract_prepared_no_adapter",
                "evaluate_address_local_read_adapter_behind_guard",
                "address_local_read_adapter_diagnostic_no_route_change",
                true,
                true,
                false,
                List.of(
                        new TableExpansionDecision(
                                "pessoa",
                                "id_pessoa",
                                List.of(
                                        "id_pessoa",
                                        "id_escola",
                                        "escola_nome",
                                        "nome_completo",
                                        "cpf",
                                        "rg",
                                        "orgao_emissor_rg",
                                        "uf_rg",
                                        "email",
                                        "telefone",
                                        "data_nascimento",
                                        "sexo",
                                        "nome_social",
                                        "nacionalidade",
                                        "naturalidade",
                                        "ativo",
                                        "created_at",
                                        "updated_at"),
                                List.of("catalogo_local_tipo_pessoa_reconciliado"),
                                List.of("buscarPorId"),
                                false,
                                true,
                                true,
                                true,
                                "identity_local_read_closed_for_current_scope"),
                        new TableExpansionDecision(
                                "pessoa_tipo_pessoa",
                                "id_pessoa_tipo_pessoa",
                                List.of("id_pessoa_tipo_pessoa", "id_pessoa", "id_tipo_pessoa", "created_at"),
                                List.of("pessoa", "tipo_pessoa"),
                                List.of("buscarPorId"),
                                false,
                                true,
                                true,
                                true,
                                "identity_local_read_dependency_closed_for_current_scope"),
                        new TableExpansionDecision(
                                "aluno",
                                "id_aluno",
                                List.of(
                                        "id_aluno",
                                        "nome_completo",
                                        "cpf",
                                        "email",
                                        "telefone",
                                        "data_nascimento",
                                        "created_at",
                                        "id_pessoa"),
                                List.of("pessoa"),
                                List.of("consultarCadastro"),
                                false,
                                true,
                                true,
                                true,
                                "consultarCadastro_guarded_read_cutover_closed"),
                        new TableExpansionDecision(
                                "responsavel",
                                "id_responsavel",
                                List.of(
                                        "id_responsavel",
                                        "nome_completo",
                                        "cpf",
                                        "email",
                                        "telefone",
                                        "created_at",
                                        "id_pessoa"),
                                List.of("pessoa"),
                                List.of("consultarCadastro"),
                                false,
                                true,
                                true,
                                true,
                                "consultarCadastro_guarded_read_cutover_closed"),
                        new TableExpansionDecision(
                                "aluno_responsavel",
                                "id_aluno_responsavel",
                                List.of(
                                        "id_aluno_responsavel",
                                        "id_aluno",
                                        "id_responsavel",
                                        "created_at"),
                                List.of("aluno", "responsavel"),
                                List.of("consultarCadastro"),
                                false,
                                true,
                                true,
                                true,
                                "consultarCadastro_guarded_read_cutover_closed"),
                        new TableExpansionDecision(
                                "endereco",
                                "id_endereco",
                                List.of(
                                        "id_endereco",
                                        "cep",
                                        "logradouro",
                                        "numero",
                                        "complemento",
                                        "bairro",
                                        "cidade",
                                        "uf",
                                        "created_at",
                                        "updated_at"),
                                List.of("pessoa_endereco", "tipo_endereco"),
                                List.of("addressLocalReadContract"),
                                false,
                                true,
                                true,
                                false,
                                "address_local_read_port_contract_prepared_no_adapter"),
                        new TableExpansionDecision(
                                "pessoa_endereco",
                                "id_pessoa_endereco",
                                List.of(
                                        "id_pessoa_endereco",
                                        "id_pessoa",
                                        "id_endereco",
                                        "id_tipo_endereco",
                                        "principal",
                                        "created_at"),
                                List.of("pessoa", "endereco", "tipo_endereco"),
                                List.of("addressLocalReadContract"),
                                false,
                                true,
                                true,
                                false,
                                "address_local_read_port_contract_prepared_no_adapter")),
                List.of(
                        "keep-consultarCadastro-guarded-local-read-closed",
                        "phase-68-formally-closed",
                        "address-schema-migration-opt-in-prepared",
                        "address-backfill-reconciliation-opt-in-prepared",
                        "address-local-read-contract-diagnostic-started",
                        "address-local-read-port-and-dto-prepared",
                        "address-local-read-payload-must-be-internal-only",
                        "address-local-read-guard-must-stay-independent-from-consultarCadastro",
                        "address-schema-columns-defined",
                        "reconciliation-key-by-pessoa-endereco-defined",
                        "principal-address-rule-defined",
                        "multiple-principal-addresses-block-green-reconciliation",
                        "address-consumers-mapped-in-monolith-before-local-read-model",
                        "internal-address-contract-defined-without-jpa-entities",
                        "separate-cep-lookup-from-persisted-address-read-model",
                        "viacep-excluded-from-local-read-model-authority",
                        "keep-address-orphan-cleanup-on-monolith-until-write-authority-is-defined",
                        "define-reconciliation-by-person-address-link-before-backfill",
                        "keep-school-scope-as-copied-identifier-without-people-service-owning-tenant",
                        "keep-pii-read-model-without-public-exposure",
                        "keep-monolith-as-authority-for-all-address-writes"),
                List.of(
                        "funcionario",
                        "professor",
                        "endereco",
                        "pessoa_endereco",
                        "pessoa_documento"),
                List.of(
                        "do-not-add-address-route-or-bff-cutover-in-this-phase",
                        "disable-people.shadow.local-persistence.migration-enabled",
                        "keep-pessoa-identity-local-read-on-monolith-fallback",
                        "disable-people.shadow.local-persistence.read-model-cutover-enabled",
                        "keep-consultarCadastro-on-monolith-proxy-when-guard-is-not-green",
                        "disable-people.shadow.local-persistence.backfill-enabled",
                        "disable-people.shadow.local-persistence.reconciliation-enabled",
                        "disable-people.shadow.local-persistence.enabled-if-operational-risk-appears"));
    }
}
