import { DashboardPublicoCodigo } from './dashboard.model';

export interface DashboardWidgetCatalogItem {
  codigo: string;
  titulo: string;
  tipoWidget: 'CARD' | 'LISTA' | 'GRAFICO' | 'ALERTA' | 'TABELA';
  ordem: number;
  queryReferencia: string;
  descricao: string;
  publicos: Array<DashboardPublicoCodigo | 'GERAL'>;
}

export const DASHBOARD_WIDGET_CATALOG: DashboardWidgetCatalogItem[] = [
  {
    codigo: 'TOTAL_MATRICULAS',
    titulo: 'Matrículas',
    tipoWidget: 'CARD',
    ordem: 1,
    queryReferencia: 'metric-total-matriculas',
    descricao: 'Total geral de matrículas no público selecionado.',
    publicos: ['ACADEMICO', 'DIRETOR'],
  },
  {
    codigo: 'MATRICULAS_SOLICITADAS',
    titulo: 'Solicitadas',
    tipoWidget: 'CARD',
    ordem: 1,
    queryReferencia: 'metric-solicitadas',
    descricao: 'Matrículas solicitadas para rotina da secretaria.',
    publicos: ['SECRETARIA'],
  },
  {
    codigo: 'MATRICULAS_EM_ANDAMENTO',
    titulo: 'Em andamento',
    tipoWidget: 'CARD',
    ordem: 2,
    queryReferencia: 'metric-em-andamento',
    descricao: 'Matrículas em andamento.',
    publicos: ['SECRETARIA'],
  },
  {
    codigo: 'DOCUMENTOS_PENDENTES',
    titulo: 'Documentos pendentes',
    tipoWidget: 'CARD',
    ordem: 3,
    queryReferencia: 'metric-documentos',
    descricao: 'Matrículas ou processos com pendência documental.',
    publicos: ['ACADEMICO', 'SECRETARIA'],
  },
  {
    codigo: 'TRANSFERENCIAS',
    titulo: 'Transferências',
    tipoWidget: 'CARD',
    ordem: 4,
    queryReferencia: 'metric-transferencias',
    descricao: 'Transferências registradas no período.',
    publicos: ['SECRETARIA'],
  },
  {
    codigo: 'MATRICULAS_PENDENTES',
    titulo: 'Pendentes',
    tipoWidget: 'CARD',
    ordem: 2,
    queryReferencia: 'metric-pendentes',
    descricao: 'Matrículas pendentes para visão executiva.',
    publicos: ['DIRETOR'],
  },
  {
    codigo: 'ALUNOS_ATIVOS',
    titulo: 'Alunos ativos',
    tipoWidget: 'CARD',
    ordem: 3,
    queryReferencia: 'metric-alunos-ativos',
    descricao: 'Quantidade de alunos ativos.',
    publicos: ['DIRETOR'],
  },
  {
    codigo: 'TURMAS_ATIVAS',
    titulo: 'Turmas ativas',
    tipoWidget: 'CARD',
    ordem: 4,
    queryReferencia: 'metric-turmas-ativas',
    descricao: 'Quantidade de turmas ativas.',
    publicos: ['DIRETOR'],
  },
  {
    codigo: 'MATRICULAS_CONCLUIDAS',
    titulo: 'Concluídas',
    tipoWidget: 'CARD',
    ordem: 3,
    queryReferencia: 'metric-concluidas',
    descricao: 'Matrículas concluídas.',
    publicos: ['ACADEMICO'],
  },
  {
    codigo: 'APTAS_REMATRICULA',
    titulo: 'Aptas para rematrícula',
    tipoWidget: 'CARD',
    ordem: 4,
    queryReferencia: 'metric-rematricula',
    descricao: 'Matrículas aptas para renovação.',
    publicos: ['ACADEMICO'],
  },
  {
    codigo: 'MATRICULAS_POR_STATUS',
    titulo: 'Matrículas por status',
    tipoWidget: 'GRAFICO',
    ordem: 10,
    queryReferencia: 'chart-status',
    descricao: 'Gráfico de pizza com matrículas por status.',
    publicos: ['GERAL'],
  },
  {
    codigo: 'VAGAS_DISPONIVEIS',
    titulo: 'Vagas disponíveis',
    tipoWidget: 'GRAFICO',
    ordem: 20,
    queryReferencia: 'chart-vagas',
    descricao: 'Gráfico de colunas com vagas disponíveis por turma.',
    publicos: ['GERAL'],
  },
  {
    codigo: 'TENDENCIA_OPERACIONAL',
    titulo: 'Tendência operacional',
    tipoWidget: 'GRAFICO',
    ordem: 30,
    queryReferencia: 'chart-tendencia',
    descricao: 'Gráfico de linha com histórico operacional.',
    publicos: ['GERAL'],
  },
  {
    codigo: 'STATUS_DAS_MATRICULAS',
    titulo: 'Status das matrículas',
    tipoWidget: 'LISTA',
    ordem: 40,
    queryReferencia: 'list-status',
    descricao: 'Lista compacta da distribuição de matrículas por status.',
    publicos: ['GERAL'],
  },
  {
    codigo: 'TURMAS_COM_VAGAS',
    titulo: 'Turmas com vagas',
    tipoWidget: 'LISTA',
    ordem: 50,
    queryReferencia: 'list-vagas',
    descricao: 'Lista compacta de turmas com vagas disponíveis.',
    publicos: ['GERAL'],
  },
  {
    codigo: 'DOCUMENTOS_E_HISTORICO',
    titulo: 'Documentos e histórico',
    tipoWidget: 'CARD',
    ordem: 60,
    queryReferencia: 'panel-documentos',
    descricao: 'Painel resumido de documentos, boletins e históricos.',
    publicos: ['GERAL'],
  },
  {
    codigo: 'RESULTADO_ACADEMICO',
    titulo: 'Resultado acadêmico',
    tipoWidget: 'CARD',
    ordem: 70,
    queryReferencia: 'panel-resultado',
    descricao: 'Painel resumido de aprovados, reprovados e alertas.',
    publicos: ['GERAL'],
  },
  {
    codigo: 'SETOR_ACADEMICO',
    titulo: 'Acadêmico',
    tipoWidget: 'CARD',
    ordem: 80,
    queryReferencia: 'sector-academico',
    descricao: 'Setor acadêmico da visão da direção.',
    publicos: ['DIRETOR'],
  },
  {
    codigo: 'SETOR_ADMINISTRATIVO',
    titulo: 'Administrativo',
    tipoWidget: 'CARD',
    ordem: 90,
    queryReferencia: 'sector-administrativo',
    descricao: 'Setor administrativo da visão da direção.',
    publicos: ['DIRETOR'],
  },
  {
    codigo: 'SETOR_PEDAGOGICO',
    titulo: 'Pedagógico',
    tipoWidget: 'CARD',
    ordem: 100,
    queryReferencia: 'sector-pedagogico',
    descricao: 'Setor pedagógico da visão da direção.',
    publicos: ['DIRETOR'],
  },
  {
    codigo: 'ALERTAS',
    titulo: 'Alertas',
    tipoWidget: 'ALERTA',
    ordem: 110,
    queryReferencia: 'panel-alertas',
    descricao: 'Painel de alertas operacionais.',
    publicos: ['GERAL'],
  },
];
